# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Savalera 
email: info@savalera.com
description: > # this means to ignore newlines until "baseurl:"
  Savalera is a digital transformation and IT services company.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://savalera.com" # the base hostname & protocol for your site
twitter_username: takacsmark

# Build settings
markdown: kramdown

google_analytics: UA-41064919-5
